---
applications:
- name: project-monitor-production
  memory: 512M
  instances: 1
  host: project-monitor-production
  path: ../../
  command: bundle exec rake db:migrate && bundle exec unicorn -p $PORT -c ./config/unicorn.rb
  services:
  - project-monitor-production
- name: project-monitor-production-worker
  memory: 256M
  instances: 1
  path: ../../
  command: bundle exec rake jobs:work
  no-route: true
  services:
  - project-monitor-production
- name: project-monitor-production-clockwork
  memory: 256M
  instances: 1
  path: ../../
  command: bundle exec clockwork ./clockwork.rb
  no-route: true
  services:
  - project-monitor-production

